project_id = "framework-doctor"

[api]
enabled = true
port = 54321
schemas = ["public"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[functions.telemetry]
verify_jwt = false
